package com.fitx.app.util

object FoodImageResolver {
    private const val TWEMOJI_BASE =
        "https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/"

    private val keywordToCode = listOf(
        "egg" to "1f95a",
        "omelette" to "1f95a",
        "scrambled" to "1f95a",
        "chicken" to "1f357",
        "turkey" to "1f983",
        "beef" to "1f356",
        "mutton" to "1f356",
        "pork" to "1f356",
        "salmon" to "1f41f",
        "tuna" to "1f41f",
        "fish" to "1f41f",
        "shrimp" to "1f990",
        "prawn" to "1f990",
        "crab" to "1f980",
        "paneer" to "1f9c0",
        "tofu" to "1f96c",
        "tempeh" to "1f96c",
        "soy" to "1f33f",
        "lentil" to "1fad8",
        "chickpea" to "1fad8",
        "bean" to "1fad8",
        "rajma" to "1fad8",
        "chole" to "1fad8",
        "dal" to "1f35b",
        "sambar" to "1f35b",
        "hummus" to "1f9c6",
        "rice" to "1f35a",
        "quinoa" to "1f35a",
        "khichdi" to "1f35b",
        "biryani" to "1f35b",
        "poha" to "1f35a",
        "upma" to "1f35d",
        "idli" to "1f959",
        "dosa" to "1f959",
        "uttapam" to "1f959",
        "oat" to "1f963",
        "oats" to "1f963",
        "bread" to "1f35e",
        "toast" to "1f35e",
        "roti" to "1f35e",
        "chapati" to "1f35e",
        "paratha" to "1f95e",
        "pasta" to "1f35d",
        "noodle" to "1f35c",
        "sandwich" to "1f96a",
        "roll" to "1f32f",
        "banana" to "1f34c",
        "apple" to "1f34e",
        "orange" to "1f34a",
        "mango" to "1f96d",
        "papaya" to "1f96d",
        "pineapple" to "1f34d",
        "grape" to "1f347",
        "pear" to "1f350",
        "guava" to "1f34f",
        "pomegranate" to "1f34e",
        "kiwi" to "1f95d",
        "watermelon" to "1f349",
        "strawberr" to "1f353",
        "blueberr" to "1fad0",
        "raspberr" to "1fad0",
        "fruit" to "1f34e",
        "salad" to "1f957",
        "avocado" to "1f951",
        "broccoli" to "1f966",
        "spinach" to "1f96c",
        "kale" to "1f96c",
        "lettuce" to "1f96c",
        "cucumber" to "1f952",
        "tomato" to "1f345",
        "carrot" to "1f955",
        "beetroot" to "1f955",
        "cauliflower" to "1f966",
        "cabbage" to "1f96c",
        "mushroom" to "1f344",
        "onion" to "1f9c5",
        "pepper" to "1fad1",
        "okra" to "1f952",
        "zucchini" to "1f952",
        "eggplant" to "1f346",
        "pumpkin" to "1f383",
        "gourd" to "1f952",
        "corn" to "1f33d",
        "milk" to "1f95b",
        "cheese" to "1f9c0",
        "yogurt" to "1f95b",
        "curd" to "1f95b",
        "lassi" to "1f964",
        "smoothie" to "1f964",
        "juice" to "1f9c3",
        "coffee" to "2615",
        "tea" to "1f375",
        "whey" to "1f964",
        "casein" to "1f964",
        "protein" to "1f964",
        "bar" to "1f36b",
        "chocolate" to "1f36b",
        "biscuit" to "1f36a",
        "samosa" to "1f35f",
        "pakora" to "1f35f",
        "vada" to "1f35f",
        "fries" to "1f35f",
        "popcorn" to "1f37f",
        "butter" to "1f9c8",
        "ghee" to "1f9c8",
        "oil" to "1fad9",
        "olive" to "1fad2",
        "peanut" to "1f95c",
        "almond" to "1f330",
        "cashew" to "1f95c",
        "walnut" to "1f330",
        "pistachio" to "1f95c",
        "chia" to "1f33f",
        "flax" to "1f33f",
        "sunflower" to "1f33b",
        "seed" to "1f33f",
        "chutney" to "1f944",
        "curry" to "1f35b",
        "drink" to "1f964"
    )

    fun imageUrlFor(foodName: String): String? {
        val normalized = foodName.trim().lowercase().replace(Regex("[^a-z0-9 ]"), " ")
        if (normalized.isBlank()) return null
        val match = keywordToCode.firstOrNull { (keyword, _) ->
            normalized.contains(keyword)
        } ?: return null
        return "$TWEMOJI_BASE${match.second}.png"
    }
}
