package com.fitx.app.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF3A86FF)
val OnPrimaryLight = Color(0xFFFFFFFF)
val SecondaryLight = Color(0xFF3A86FF)
val OnSecondaryLight = Color(0xFFFFFFFF)
val TertiaryLight = Color(0xFF3A86FF)
val OnTertiaryLight = Color(0xFFFFFFFF)
val SurfaceLight = Color(0xFFFCFDFF)
val SurfaceVariantLight = Color(0xFFE8EDF5)
val BackgroundLight = Color(0xFFF2F5FA)
val OnBackgroundLight = Color(0xFF121721)
val OnSurfaceLight = Color(0xFF121721)
val OnSurfaceVariantLight = Color(0xFF4B596B)
val OutlineLight = Color(0xFF8D9AAF)
val ErrorLight = Color(0xFFB3261E)
val OnErrorLight = Color(0xFFFFFFFF)

val PrimaryDark = Color(0xFF3A86FF)
val OnPrimaryDark = Color(0xFFF7FAFF)
val SecondaryDark = Color(0xFF3A86FF)
val OnSecondaryDark = Color(0xFFF7FAFF)
val TertiaryDark = Color(0xFF3A86FF)
val OnTertiaryDark = Color(0xFFF7FAFF)
val SurfaceDark = Color(0xFF1A2028)
val SurfaceVariantDark = Color(0xFF242C36)
val BackgroundDark = Color(0xFF12161D)
val OnBackgroundDark = Color(0xFFE9EEF7)
val OnSurfaceDark = Color(0xFFE9EEF7)
val OnSurfaceVariantDark = Color(0xFFAAB5C5)
val OutlineDark = Color(0xFF4D5B6E)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
